#server:
#  port: 8081
#
#person:
#  lastname: xiaoming
#  age: 24
#  boss: false
#  birth: 2020/03/17
#  maps: {k1: v1,k2: v2}
#  lists:
#    - xiaohong
#    - xiaowang
#    - zhangsan
#  mdog:
#    name: jhon小狗
#    age: 2